tls:
  certificates:
    - certFile: "/etc/certs/wpds.localtest.me.crt"
      keyFile: "/etc/certs/wpds.localtest.me.key"

http:
  routers:
    traefik:
      rule: "Host(`traefik.wpds.localtest.me`)"
      entryPoints:
        - websecure
      service: "api@internal"
      tls: {}