global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

log:
  level: DEBUG
  format: common

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"